// THIS FILE IS AUTO-GENERATED BY KEYCLOAKIFY — DO NOT EDIT MANUALLY.
// Run `npm run build` to regenerate after changing vite.config.ts theme options.
//
// This stub satisfies TypeScript during development. The real file is generated
// by the keycloakify vite plugin when you run the build.

export type ThemeName = "boilerplate-keycloak";

// KcEnvName lists the names of theme properties you've declared in vite.config.ts
// under keycloakify.environmentVariables. Add entries here as you add env vars.
export type KcEnvName = never;

// KcPage is the union of login + account page components. The real generated
// version re-exports from both themes with proper typing.
export { default as KcPage } from "./login/KcPage";
