import { createRoot } from "react-dom/client";
import { StrictMode, lazy, Suspense } from "react";

// kc.gen.ts is auto-generated by `npm run build` (keycloakify vite plugin).
// It exports KcPage which routes to login or account based on window.kcContext.
const KcLoginPage = lazy(() => import("./login/KcPage"));
const KcAccountPage = lazy(() => import("./account/KcPage"));

function App() {
    const kcContext = (window as any).kcContext;

    if (!kcContext) {
        return (
            <div style={{ padding: "2rem", fontFamily: "sans-serif" }}>
                <h1>No Keycloak Context</h1>
                <p>
                    This app is a Keycloak theme. It must be loaded inside Keycloak or via
                    Storybook mock mode.
                </p>
            </div>
        );
    }

    return (
        <Suspense>
            {kcContext.themeType === "account" ? (
                <KcAccountPage kcContext={kcContext} />
            ) : (
                <KcLoginPage kcContext={kcContext} />
            )}
        </Suspense>
    );
}

createRoot(document.getElementById("root")!).render(
    <StrictMode>
        <App />
    </StrictMode>
);
